---
title: "Train"
author: "Peters"
date: "9/16/2020"
output: html_document
---

```{r}
library(tidyverse)
library(DataExplorer)
library(caret)

train <- read_csv("train.csv")
test <- read_csv("test.csv")

(phil <- bind_rows(train = train, test = test, .id="Set"))
```

```{r}
head(phil)
```

```{r}
sum(is.na(phil$PSSM))
sum(is.na(phil$Consensus))

phil[is.na(phil$PSSM), ]
phil[!is.na(phil$PSSM), ]
```

```{r}
summary(phil)

plot_correlation(phil, type="continuous", 
                 cor_args=list(use="pairwise.complete.obs"))
```


```{r}
ggplot(data = phil, mapping=aes(x=SVM, PSSM)) + geom_point() + ggtitle("SVM vs PSSM")
ggplot(data = phil, mapping=aes(x=ANN, PSSM)) + geom_point() + ggtitle("ANN vs PSSM")
```


### Stochastic Regression imputation for PSSM
```{r}
summary(lmobj <- lm(PSSM~SVM+ANN, data = phil))

PSSM.preds <- (predict(lmobj, newdata=(phil %>% filter(is.na(PSSM))))+
                  rnorm(sum(is.na(phil$PSSM)), 0, sigma(lmobj)))

phil <- phil %>%
  mutate(PSSM=replace(PSSM, is.na(PSSM), PSSM.preds))

sum(is.na(phil$PSSM))

```

```{r}
ggplot(data = phil, mapping=aes(x=SVM, PSSM)) + geom_point() + ggtitle("SVM vs PSSM")
ggplot(data = phil, mapping=aes(x=ANN, PSSM)) + geom_point() + ggtitle("ANN vs PSSM")
```

